### ISSUE TITLE
Installation issue on Rasberry PI 3B

### ISSUE THREAD

**Issue by jewendt** [somebuddy87/node-red-contrib-usbhid#3]
I would really like to use this but I am getting the following error on the Raspberry PI 3B.  Any suggestions?

pi@raspberrypi:~/.node-red $ npm install node-red-contrib-usbhid
(node:21900) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
\
> node-hid@0.5.7 install /home/pi/.node-red/node_modules/node-red-contrib-usbhid/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.1 runtime=node arch=arm platform=linux)
make: Entering directory '/home/pi/.node-red/node_modules/node-red-contrib-usbhid/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
                    ^
compilation terminated.
hidapi.target.mk:95: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-contrib-usbhid/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.34-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-red-contrib-usbhid/node_modules/node-hid
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script.
npm ERR! This is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.14.34-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-usbhid"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0

**Comment by Hugobox** [comment]
Hi! I had the same error and had to compile node-hid. https://www.npmjs.com/package/node-hid#compiling-from-source

**Comment by jewendt** [comment]
Hi #Hugobox.  Sorry, Node Red newbie here.  Can you provide me some instructions on how to do that?

**Comment by knolleary** [comment]
You should start by updating your version of npm - 1.4.21 is ancient and could well be the cause of these issues.

If you're using the preinstalled version of the Node-RED, you should use update script to get on to the latest levels of everything - https://nodered.org/docs/hardware/raspberrypi

**Comment by jewendt** [comment]
Sorry #knolleary should have pasted the updated error message.  Here you go with a fully updated PI.

28 Sep 19:56:34 - [info] Installing module: node-red-contrib-usbhid, version: 0.0.1
28 Sep 19:57:07 - [warn] Installation of module node-red-contrib-usbhid failed:
28 Sep 19:57:07 - [warn] ------------------------------------------
28 Sep 19:57:07 - [warn]
> node-hid@0.5.7 install /home/pi/.node-red/node_modules/node-hid
> prebuild-install || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=8.12.0 runtime=node arch=arm platform=linux)
make: Entering directory '/home/pi/.node-red/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
                    ^
compilation terminated.
hidapi.target.mk:101: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: Leaving directory '/home/pi/.node-red/node_modules/node-hid/build'
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.50-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-hid
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@0.5.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-09-29T00_57_07_513Z-debug.log
28 Sep 19:57:07 - [warn] ------------------------------------------

**Comment by Hugobox** [comment]
Basically, node-hid doesn't come with pre-built binaries for Linux ARM so you need to do that manually. Just follow the link I sent, look for the "Compiling from source" section, and after a few trial and error, googling of said errors, you should be able to get it working!

**Comment by jewendt** [comment]
Thanks!  I did get it working.  Here are the details for other newbies like me.  Don't exactly understand everything here but it worked!  After the below steps all you need to do is reboot and install the USBHID Nodes

pi@100S_QA_PI:~ $ cd \.node-red
pi@100S_QA_PI:~/.node-red $ sudo npm install -g node-gyp
pi@100S_QA_PI:~/.node-red $ sudo apt install libusb-1.0-0 libusb-1.0-0-dev
pi@100S_QA_PI:~/.node-red $ sudo apt-get install libudev-dev
pi@100S_QA_PI:~/.node-red $ sudo npm install node-hid --build-from-source --unsafe-perm
pi@100S_QA_PI:~/.node-red $ sudo mkdir -p /etc/udev/rules.d
pi@100S_QA_PI:~/.node-red $ sudo nano /etc/udev/rules.d/85-pure-data.rules
SUBSYSTEM=="usb", GROUP="input", MODE="777"
pi@100S_QA_PI:~/.node-red $ 
pi@100S_QA_PI:~/.node-red $ sudo groupadd -f input
pi@100S_QA_PI:~/.node-red $ 
pi@100S_QA_PI:~/.node-red $ sudo gpasswd -a pi input

**Comment by Meptik** [comment]
@jewendt I've been running into this same issue but can't seem to get past similar issues. Not sure if anyone can help provide any insight?

-----

npm install node-red-contrib-usb

usb@1.5.0 install /home/pi/node_modules/usb
node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.5.0/usb_bindings-v1.5.0-node-v64-linux-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for usb@1.5.0 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/pi/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
  AR(target) Release/obj.target/usb.a
  COPY Release/usb.a
  CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
../src/node_usb.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE SetDebugLevel(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node_usb.cc:99:73: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  if (info.Length() != 1 || !info[0]->IsUint32() || info[0]->Uint32Value() > 4) {
                                                                         ^
In file included from /home/pi/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from ../src/node_usb.h:12,
                 from ../src/node_usb.cc:1:
/home/pi/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/pi/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node_usb.cc:103:53: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  libusb_set_debug(usb_context, info[0]->Uint32Value());
                                                     ^
In file included from /home/pi/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from ../src/node_usb.h:12,
                 from ../src/node_usb.cc:1:
/home/pi/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/pi/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/node_usb.cc: In function ‘void handleHotplug(std::pair<libusb_device*, libusb_hotplug_event>)’:
../src/node_usb.cc:151:58: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::New(hotplugThis), "emit", 2, argv);
                                                          ^
In file included from ../src/helpers.h:3:0,
                 from ../src/node_usb.h:21,
                 from ../src/node_usb.cc:1:
../../nan/nan.h:1001:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/node_usb.cc: In function ‘v8::Local<v8::Value> libusbException(int)’:
../src/node_usb.cc:301:14: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  e->ToObject()->Set(Nan::New<String>("errno").ToLocalChecked(), Nan::New<Integer>(errorno));
              ^
In file included from ../src/node_usb.h:12:0,
                 from ../src/node_usb.cc:1:
/home/pi/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
  CXX(target) Release/obj.target/usb_bindings/src/device.o
../src/device.cc: In static member function ‘static void Req::default_after(uv_work_t*)’:
../src/device.cc:237:64: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(device, Nan::New(baton->callback), 1, argv);
                                                                ^
In file included from ../src/helpers.h:3:0,
                 from ../src/node_usb.h:21,
                 from ../src/device.cc:1:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CXX(target) Release/obj.target/usb_bindings/src/transfer.o
../src/transfer.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Transfer_Submit(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/transfer.cc:58:47: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  Local<Object> buffer_obj = info[0]->ToObject();
                                               ^
In file included from ../src/node_usb.h:12:0,
                 from ../src/transfer.cc:1:
/home/pi/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/transfer.cc: In function ‘void handleCompletion(Transfer*)’:
../src/transfer.cc:126:72: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(self->handle(), Nan::New(self->v8callback), 3, argv);
                                                                        ^
In file included from ../src/helpers.h:3:0,
                 from ../src/node_usb.h:21,
                 from ../src/transfer.cc:1:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/usb_bindings.node
  COPY Release/usb_bindings.node
  COPY /home/pi/node_modules/usb/src/binding/usb_bindings.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/node_modules/usb/build'
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ node-red-contrib-usb@1.0.0
added 36 packages from 20 contributors and audited 573 packages in 107.579s
found 0 vulnerabilities

**Comment by knkrishnaprasad** [comment]
Hello All, I need help I have one issue. need your guideline and suggestions, 

I have one HID device which generate  / Transmit temperature and humidity data  over USB. I am using note-contlib-usbHid from node-red.  I am getting all device information from getHIDDevice node. that are as follows.
vendorId: 4292
productId: 34632
path: "\\?\hid#vid_10c4&pid_8748#6&f8c74c6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
serialNumber: "MTI_0001-20180402122950-F324EF"
manufacturer: "MadgeTech, Inc"
product: "Datalogger Interface"
release: 256
interface: -1
usagePage: 65280
usage: 1

Now I am tying to get temperature and humidity data , but not able to fetch. Can some one give some inputs on it.

Note : I am using following flow.



[{"id":"7e5e036c.8b53dc","type":"HIDdevice","z":"addc72f6.08a4b","connection":"7a42388b.a2cfa8","name":"KNEOHID","x":716.5,"y":298,"wires":[["92a54b4d.2cabc8"],[]]},{"id":"acccf495.9c46d8","type":"inject","z":"addc72f6.08a4b","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":362.5,"y":294,"wires":[["7e5e036c.8b53dc"]]},{"id":"92a54b4d.2cabc8","type":"debug","z":"addc72f6.08a4b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":964.5,"y":294,"wires":[]},{"id":"7a42388b.a2cfa8","type":"HIDConfig","z":"","vid":"4292","pid":"34632","name":"KNEO"}]

Best regards,
Krishna Prasad
knkrishnaprasad2@gmail.com

**Comment by janvda** [comment]
Regarding the issue:
```
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
#include <libusb.h>
```

I got this fixed by installing `libusb-1.0.0-dev` (see https://github.com/LedgerHQ/btchip-python/issues/27)
using a command like:
```
apt-get install libusb-1.0.0-dev
```

**Comment by chooimail** [comment]
> Thanks! I did get it working. Here are the details for other newbies like me. Don't exactly understand everything here but it worked! After the below steps all you need to do is reboot and install the USBHID Nodes
> 
> pi@100S_QA_PI:~ $ cd .node-red pi@100S_QA_PI:~/.node-red $ sudo npm install -g node-gyp pi@100S_QA_PI:~/.node-red $ sudo apt install libusb-1.0-0 libusb-1.0-0-dev pi@100S_QA_PI:~/.node-red $ sudo apt-get install libudev-dev pi@100S_QA_PI:~/.node-red $ sudo npm install node-hid --build-from-source --unsafe-perm pi@100S_QA_PI:~/.node-red $ sudo mkdir -p /etc/udev/rules.d pi@100S_QA_PI:~/.node-red $ sudo nano /etc/udev/rules.d/85-pure-data.rules SUBSYSTEM=="usb", GROUP="input", MODE="777" pi@100S_QA_PI:~/.node-red $ pi@100S_QA_PI:~/.node-red $ sudo groupadd -f input pi@100S_QA_PI:~/.node-red $ pi@100S_QA_PI:~/.node-red $ sudo gpasswd -a pi input


Just to share my own experience here.
Coming from this point in the Node-red forum: https://discourse.nodered.org/t/raspberry-pi-usb-hid-node-error/19410/6

Installed on: RPi4 model B
1. Follow all the prerequisites as listed : https://flows.nodered.org/node/node-red-contrib-usbhid

- sudo apt install libusb-1.0-0 libusb-1.0-0-dev libudev-dev
- npm install node-hid  (from https://github.com/node-hid/node-hid)

2. Create a new file : sudo nano /etc/udev/rules.d/85-pure-data.rules
3. Type-in : SUBSYSTEM=="usb", GROUP="input", MODE="777"
4. sudo groupadd -f input
5. sudo gpasswd -a pi input
6. Reboot
7. cd .node-red
8. npm install node-red-contrib-usbhid
**Probably have to use this if above not working... npm install robertsLando/node-red-contrib-usbhid)

Start Node-red
9. Build the flow
10. If the HID shows not connected...

- sudo chown -R pi:pi /dev/hidraw*

I'm not permanently using this myself.
So I'm guessing there should be a better way to permanently allow the user to have read-write access to the path /dev/hidraw*

What comes next after this is "translating" the output to something readible.
This is still a work in progress.
As far as I can compare against a Serial comm output, it is NOT the same.
Rather, it is similar to what I have glanced through over here so far. (link below)
https://docs.zephyrproject.org/2.7.0/reference/usb/hid.html
